### ISSUE TITLE
Update README to use `append :linked_files, ".env"`

### ISSUE THREAD

**Issue by koffeinfrei** [panter/panter-rails-deploy#10]
The [documented way](http://capistranorb.com/documentation/getting-started/configuration/) (>= capistrano 3.5) to use `linked_dir` and `linked_file` is `append :linked_files, ".env"`.
Or is there a reason to use `set :linked_files, fetch(:linked_files, []).push('.env')`? Do we need to support < 3.5?

**Comment by toupeira** [comment]
Ah nice, this is a new feature in Capistrano 3.5. Updated the README and released 1.3.0, not sure if I'm doing semver correctly :)
