### ISSUE TITLE
support / migrate to puma as app server

### ISSUE THREAD

**Issue by domicode** [panter/panter-rails-deploy#14]
since puma is default server in rails 5.x.x and is more performant it would be a good idea in my opinion to support or even migrate to it.

**Comment by koffeinfrei** [comment]
The whole panter deployment setup is based on unicorn, including all scripts etc. @jeredepp What's the feasibility of this? We'd need to support both rails setups.

**Comment by toupeira** [comment]
Yeah there's some Unicorn-specific stuff in our cdist configuration, but it should be possible to support both/other servers without too much effort. The main thing we want to keep from Unicorn is the ability to do zero-downtime deploys, which is possible with Puma too (and looks easier as well) but requires some testing.

**Comment by toupeira** [comment]
Closing in favor of Kubernetes :)
