### ISSUE TITLE
Add `highline` gem

### ISSUE THREAD

**Issue by huerlisi** [panter/panter-rails-deploy#9]
Stock capistrano does not hide input for password prompts. This can be fixed by including the `highline` gem.

This is suggested by capistrano when running `cap deploy` and some prompt for SSH or similar is shown:
```
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
```

**Comment by toupeira** [comment]
Thanks! :)

**Comment by huerlisi** [comment]
:+1: Thx!
